// RabbitaAI Agent — Powered by Google Gen AI SDK (Vertex AI Express)
// Uses @google/genai — the new unified SDK supporting both AI Studio and Vertex Express API keys.
// Vertex Express keys (AQ.*) work without billing, giving us Vertex-grade infrastructure for free.
require('dotenv').config();
const { GoogleGenAI } = require('@google/genai');

let genAI = null;

function getClient() {
  if (!genAI) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error('GEMINI_API_KEY not set in backend/.env');
    genAI = new GoogleGenAI({ apiKey });
  }
  return genAI;
}

async function generateText(prompt) {
  const client = getClient();
  // Fallback chain: Prioritize 3.5-flash for maximum intelligence and "vibe".
  // If quota runs out or Google has an outage, fall back to standard flash, then flash-lite.
  const fallbackOrder = [
    'gemini-3.5-flash',
    'gemini-2.5-flash',
    'gemini-flash-latest',
    'gemini-2.5-flash-lite',
    'gemini-flash-lite-latest'
  ];

  let lastError = null;
  for (const modelName of fallbackOrder) {
    try {
      const response = await client.models.generateContent({
        model: modelName,
        contents: prompt,
      });
      return response.text;
    } catch (e) {
      console.warn(`[GEMINI] Model ${modelName} failed: ${e.message}. Trying next...`);
      lastError = e;
    }
  }

  throw new Error(`All models failed. Last error: ${lastError.message}`);
}

// ─── DETERMINISTIC PRE-FILTERS ─────────────────────────────────────────────────
// These catch obvious patterns BEFORE calling Gemini. 100% reliable, zero latency.

// Matches: hi, hii, hey, heyyy, hello, helloo, yo, yoo, sup, wassup, good morning, etc.
const GREETING_RE = /^\s*(h+e+y+|h+i+|h+e+l+o+|yo+|s+u+p+|w+[ah]+s+u+p+|good\s*(morning|evening|afternoon|night)|thanks?|thank\s*you|ok+a*y*|great|cool|nice|yup|yep|yeah?|ye+s+|no+|nah|nope|alright|aight)\s*[!?.,:;\s🙏👋😊🥰❤️]*\s*$/i;

// Matches vague mood/feeling statements that need clarification, not search
const VAGUE_MOOD_RE = /^\s*(i'?m\s+(hungry|bored|tired|feeling|craving|looking)|i\s+need\s+(something|someone|help)|i\s+want\s+something|help\s*me?)\s*[!?.]*\s*$/i;

// Words that should NEVER appear in Google Maps search queries
const BANNED_QUERY_WORDS = new Set([
  'hi', 'hey', 'hello', 'yo', 'sup', 'thanks', 'ok', 'yes', 'no', 'yup', 'nope',
  'hungry', 'tired', 'bored', 'feeling', 'help', 'something', 'someone', 'good', 'morning',
  'evening', 'afternoon', 'night', 'well', 'great', 'cool', 'nice',
]);

/**
 * Pre-filter: detect greetings deterministically.
 * Returns a chat intent object if matched, or null if Gemini should handle it.
 */
function preFilterGreeting(text) {
  if (GREETING_RE.test(text)) {
    return {
      action: 'chat',
      conversationalResponse: null, // will be generated by generateHelpMessage
      searchQueries: [],
      primaryQuery: '',
      clarificationQuestion: null,
      urgency: 'low',
      context: 'greeting',
      specificRequirements: '',
      userIntent: 'greeting',
    };
  }
  return null;
}

/**
 * Pre-filter: detect vague mood statements that need clarification.
 */
function preFilterVagueMood(text) {
  if (VAGUE_MOOD_RE.test(text)) {
    // Map common moods to clarification prompts
    const lower = text.toLowerCase();
    let response = "What can I help you with? 😊";
    if (/hungry|craving|food/i.test(lower)) {
      response = "What are you in the mood for? 🍕 Pizza, biryani, something light?";
    } else if (/bored/i.test(lower)) {
      response = "Want me to find food, activities, or something fun nearby? 🎯";
    } else if (/tired/i.test(lower)) {
      response = "Want to order food, book a massage, or something else? 💆";
    } else if (/need\s+(someone|help)/i.test(lower)) {
      response = "Someone for what — cleaning, repairs, delivery? 🔧";
    }

    return {
      action: 'clarify',
      conversationalResponse: response,
      searchQueries: [],
      primaryQuery: '',
      clarificationQuestion: response,
      urgency: 'low',
      context: lower,
      specificRequirements: '',
      userIntent: lower,
    };
  }
  return null;
}

/**
 * Post-filter: validate Gemini's output. If it says "search" but the queries
 * look like raw user text or contain banned words, override to "clarify".
 */
function postFilterIntent(intent, originalText) {
  if (intent.action !== 'search') return intent;

  const queries = intent.searchQueries || [];
  const primary = (intent.primaryQuery || '').toLowerCase().trim();

  // Check 1: primaryQuery is suspiciously long (likely a hallucinated raw sentence instead of a category)
  if (primary.length > 40) {
    console.warn(`[POST-FILTER] primaryQuery is too long to be a category: "${primary}". Overriding to clarify.`);
    return {
      ...intent,
      action: 'clarify',
      conversationalResponse: intent.conversationalResponse || "Could you tell me more about what you're looking for? 🤔",
      clarificationQuestion: intent.conversationalResponse || "Could you tell me more about what you're looking for?",
    };
  }

  // Check 2: searchQueries contain ONLY banned words (e.g. "hey", "good morning")
  const hasBannedQuery = queries.some(q => {
    const words = q.toLowerCase().split(/\s+/);
    return words.length > 0 && words.every(w => BANNED_QUERY_WORDS.has(w));
  });

  if (hasBannedQuery) {
    console.warn(`[POST-FILTER] searchQueries contain ONLY banned words: ${JSON.stringify(queries)}. Overriding to clarify.`);
    return {
      ...intent,
      action: 'clarify',
      conversationalResponse: intent.conversationalResponse || "What exactly are you looking for? I can find anything nearby! 😊",
      clarificationQuestion: intent.conversationalResponse || "What exactly are you looking for?",
    };
  }

  return intent;
}

/**
 * Full intent analysis with deterministic guardrails.
 * Flow: Pre-filter → Gemini → Post-filter
 */
async function analyzeIntent(requestText, locationContext = {}, conversationHistory = '') {
  // ── LAYER 1: Deterministic pre-filters (100% reliable, instant) ──────────
  const greetingIntent = preFilterGreeting(requestText);
  if (greetingIntent) {
    console.log(`[PRE-FILTER] Greeting detected: "${requestText}"`);
    return greetingIntent;
  }

  const moodIntent = preFilterVagueMood(requestText);
  if (moodIntent) {
    console.log(`[PRE-FILTER] Vague mood detected: "${requestText}"`);
    return moodIntent;
  }
  // ── LAYER 2: Gemini AI analysis (for genuinely ambiguous input) ──────────
  const city = locationContext.city || 'their area';
  const country = locationContext.country || 'their country';
  const language = locationContext.language || 'English';

  const prompt = `You are RabbitaAI — a warm, intelligent AI that helps people find and book local services. You think like a smart, resourceful local friend.

User Location: ${city}, ${country}
Language: ${language} (Reply in ${language}!)
Conversation so far:
${conversationHistory || '(First message)'}

User says: "${requestText}"

YOUR CORE TASK — ONTOLOGY MAPPING:
Translate the user's casual language into real Google Maps business categories.
"I need biscuits" → search for "grocery store" or "supermarket", NOT "biscuit shop"
"my pipe broke" → search for "plumber"
"I want pizza" → clarify size/toppings/brand first, THEN search for "pizza restaurant"
"crown crust from cheezious" → search for "Cheezious"

DECISION RULES:
1. If user has a SPECIFIC need + enough detail → action: "search", map to proper business category
2. If user has a need but MISSING specifics (size, type, brand, problem details) → action: "clarify", ask ONE focused question
3. If user is vague (mood, feeling, "I need something") → action: "clarify", suggest options warmly
4. If you can't clearly identify a service need → action: "clarify"
5. NEVER repeat a question the user already answered in the conversation history
6. We do NOT support taxi/transport — politely decline those
7. For problems (broken things), empathize briefly then search

Respond in JSON ONLY:
{
  "action": "chat" | "search" | "clarify",
  "conversationalResponse": "warm reply to user in ${language}",
  "searchQueries": ["google maps category 1", "category 2"] (only if action is search),
  "primaryQuery": "1-3 word business category" (only if action is search, e.g. "plumber", "pizza restaurant"),
  "clarificationQuestion": "your question" (only if action is clarify, same text as conversationalResponse),
  "urgency": "low" | "medium" | "high",
  "type": "service" | "order",
  "context": "VERBATIM details of the request ready to be forwarded to the business. Include exact items, quantities, or special instructions mentioned by the user. If the user is vague (e.g. just said 'plumber'), DO NOT invent details like 'broken pipe' — just use their exact words."
}`;

  const text = await generateText(prompt);
  const cleaned = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim();


  let intent;
  try {
    const parsed = JSON.parse(cleaned);
    intent = {
      action: parsed.action || 'clarify',
      conversationalResponse: parsed.conversationalResponse || '',
      searchQueries:
        Array.isArray(parsed.searchQueries) && parsed.searchQueries.length > 0
          ? parsed.searchQueries.slice(0, 3)
          : [],
      primaryQuery: parsed.primaryQuery || '',
      clarificationQuestion: parsed.clarificationQuestion || null,
      urgency: parsed.urgency || 'low',
      type: parsed.type === 'order' ? 'order' : 'service',
      context: parsed.context || requestText,
      specificRequirements: parsed.context || '',
      userIntent: parsed.context || requestText,
    };
  } catch (err) {
    console.error('analyzeIntent JSON parse failed:', text.slice(0, 300));
    // SAFE fallback: clarify, never blindly search
    intent = {
      action: 'clarify',
      conversationalResponse: "I'd love to help! Could you tell me a bit more about what you need? 😊",
      searchQueries: [],
      primaryQuery: '',
      clarificationQuestion: "Could you tell me a bit more about what you need?",
      urgency: 'low',
      type: 'service',
      context: requestText,
      specificRequirements: '',
      userIntent: requestText,
    };
  }

  // ── LAYER 3: Post-filter validation (catches AI mistakes) ────────────────
  intent = postFilterIntent(intent, requestText);

  // If action is search but searchQueries are empty, fall back to raw text mapped to a query
  if (intent.action === 'search' && intent.searchQueries.length === 0) {
    intent.searchQueries = [intent.primaryQuery || requestText];
  }

  return intent;
}

/**
 * Generate a friendly help/onboarding message when user sends a greeting or non-service input.
 */
async function generateHelpMessage(requestText, locationContext = {}) {
  const city = locationContext.city || 'your area';

  const prompt = `You are RabbitaAI, a friendly WhatsApp-style AI assistant that finds and books local services.

The user sent: "${requestText}"
User's Location: ${city}

This is NOT a service request. Write ONE short, warm reply (max 25 words) that:
1. Greets them back naturally in a human way
2. Briefly says what you do
3. Gives 2 relatable examples of what they can search for in ${city}

Return ONLY the message, no quotes.`;

  try {
    return (await generateText(prompt)).trim();
  } catch {
    return "Hey there! I'm here to help you find whatever you need locally—whether that's a plumber, a great pizza place, or anything else. What's on your mind? 😊";
  }
}

/**
 * Review-aware provider ranking.
 * Gemini reads actual review text to give genuine, helpful recommendations.
 */
async function rankProviders(requestText, intent, providers) {
  if (!providers || providers.length === 0) return [];

  const specificReqs = intent?.specificRequirements || '';
  const userIntent = intent?.userIntent || requestText;

  const providerData = providers.map((p) => ({
    placeId: p.placeId,
    name: p.name,
    rating: p.rating,
    userRatingCount: p.userRatingCount,
    distanceKm: p.distanceKm,
    address: p.address,
    phoneNumber: p.phoneNumber || null,
    isOpen: p.isOpen,
    editorialSummary: p.editorialSummary || null,
    priceLevel: p.priceLevel || null,
    topReviews: (p.reviews || []).slice(0, 3).map((r) => ({
      stars: r.rating,
      text: (r.text || '').slice(0, 200),
      timeAgo: r.timeAgo,
    })),
  }));

  const prompt = `You are RabbitaAI, a smart local service recommendation AI. Think like a knowledgeable local friend.

User wants: "${requestText}"
Specific requirements: "${specificReqs}"
What they need: "${userIntent}"

Available providers (with real Google Maps ratings and customer reviews):
${JSON.stringify(providerData, null, 2)}

Your task:
1. Pick up to 5 of the BEST providers that genuinely match what the user wants. Show more options to give the user variety.
2. STRICT BRAND RULE: If the user asked for a specific brand by name (e.g., "Cheezious", "KFC", "Pizza Hut"), you MUST ONLY return locations of that exact brand. Do NOT return competitors (e.g., if they ask for Cheezious, do not include "The Crust Pizza" or "Domino's").
3. If user wants something specific (e.g. "crown crust", "vegan"), prioritize providers whose reviews mention it.
4. If you include a provider with few reviews (<4) or a lower rating, you MUST explicitly caveat it in the explanation (e.g., "This is a newer spot with fewer reviews, but it's very close by.").
5. Write a 1-2 sentence explanation per provider that reads like genuine advice from a local friend:
   - Mention specific rating + review count.
   - Pull a real insight from the reviews if available.
   - Note if it's open now (if known).
   - Be honest — if reviews are mixed, say so.

Return ONLY a valid JSON array (no markdown):
[
  {
    "placeId": "...",
    "name": "...",
    "rating": 4.5,
    "userRatingCount": 312,
    "distanceKm": 1.2,
    "address": "...",
    "phoneNumber": "..." or null,
    "isOpen": true,
    "aiExplanation": "Rated 4.5 ⭐ with 312 reviews and only 1.2km away. Customers specifically rave about their crown crust — 'best in Lahore' shows up in multiple recent reviews.",
    "reviewHighlight": "best crown crust in Lahore"
  }
]`;

  const text = await generateText(prompt);
  const cleaned = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim();

  try {
    const parsed = JSON.parse(cleaned);
    return Array.isArray(parsed) ? parsed : [];
  } catch (err) {
    console.error('rankProviders JSON parse failed:', text.slice(0, 200));
    return providers.slice(0, 3).map((p) => ({
      ...p,
      aiExplanation: `Rated ${p.rating ?? 'N/A'} ⭐ (${p.userRatingCount || 0} reviews), ${p.distanceKm}km away.`,
      reviewHighlight: null,
    }));
  }
}

/**
 * Generate a dynamic acknowledgement after finding providers.
 */
async function generateAckMessage(requestText, intent, providerCount) {
  const what = intent?.primaryQuery || requestText;
  const prompt = `You are RabbitaAI, a friendly assistant.

User asked for: "${requestText}" (looking for: ${what})
You found ${providerCount} nearby provider(s).

Write ONE short, warm message (max 15 words) confirming you found results.
Be specific about what was found. Sound like a helpful friend, not a bot.

Examples:
- "Found 3 top-rated spots near you — take your pick! 🍕"
- "Great news! 2 plumbers are close by and ready to help 🔧"

Return ONLY the message, no quotes.`;

  try {
    return (await generateText(prompt)).trim();
  } catch {
    return `Found ${providerCount} great ${what} options near you 📍`;
  }
}

/**
 * Analyze a provider's WhatsApp reply and decide what to do next.
 */
async function analyzeProviderMessage(messageBody, bookingContext = {}) {
  const p = bookingContext.userProfile || {};

  const prompt = `You are RabbitaAI, an AI booking assistant managing WhatsApp conversations with local service providers on behalf of users. Your goal is to handle as much as possible autonomously — only escalate to the user when absolutely necessary.

Booking context:
- Request ID: ${bookingContext.requestId || 'unknown'}
- Service type: "${bookingContext.serviceQuery || 'local service'}"
- Order details (verbatim): "${bookingContext.orderDetails || bookingContext.originalRequest || ''}"
- Provider name: "${bookingContext.providerName || 'the provider'}"

FULL USER PROFILE (use this to answer provider questions without asking the user):
- Customer Name: "${p.name || 'Not provided'}"
- Customer Phone: "${p.phone || 'Not provided'}"
- Service/Delivery Address: "${p.address || 'Not provided'}"
- General Area: "${p.area || 'Not provided'}"
- Preferred Timing: "${p.timing || 'Not specified'}"
- Personal Notes / Preferences: "${p.bio || 'None'}"

The provider just sent this WhatsApp message:
"${messageBody}"

DECISION RULES (apply in order):
1. PROFILE INFO AVAILABLE → If the provider explicitly asks about address, name, or phone AND the relevant profile field above is NOT "Not provided" or empty → auto-reply with that info. No need to ask user.
2. PROFILE INFO MISSING → If the provider explicitly asks about address, name, or phone AND the relevant profile field IS "Not provided" or empty → set requiresUserInput: true and ask the user for that specific missing info.
3. ORDER DETAILS KNOWN → If the provider explicitly asks about the order details and those are clearly stated in "Order details" above → auto-reply with them.
4. TIMING EXPLICITLY ASKED → If the provider explicitly asks "when" or "what time" → If "Preferred Timing" is set, use it. If "Not specified", set requiresUserInput: true and ask the user. Do NOT ask for timing if the provider did not ask.
5. NEW OR AMBIGUOUS INFO → If the provider asks a question not covered by the profile or order details → requiresUserInput: true. Ask the user clearly.
6. BOOKING CONFIRMED (SIMPLE ACKNOWLEDGEMENT) → If the provider simply says "Okay", "Done", "Yes", or confirms the booking WITHOUT asking any questions → bookingConfirmed: true, requiresUserInput: false. Do NOT ask the user for any details.
7. CONFUSED OR UNCERTAIN → If the message is highly ambiguous but looks like a question → requiresUserInput: true. Summarize the confusion for the user.

ANTI-HALLUCINATION RULE: Never invent or assume any detail. If a field says "Not provided", treat it as unknown. Do not ask the user for information unless the provider specifically requested it.

CRITICAL FORMATTING RULES:
- suggestedReply is ONLY for messages TO THE PROVIDER. Never put user-facing text in suggestedReply.
- Do NOT ask the provider questions. If you don't know the answer, set requiresUserInput: true and suggestedReply: null.
- userPrompt is ONLY for messages TO THE USER. Must be a CLEAN, FRIENDLY question in plain English — never include the provider's raw message, never include [REQ-...] codes.
- When requiresUserInput is true, suggestedReply MUST be null.
- Keep suggestedReply professional and concise (under 40 words).
- Always prefix suggestedReply with [${bookingContext.requestId}].

Return ONLY valid JSON (no markdown):
{
  "requiresUserInput": boolean,
  "suggestedReply": "Message to provider, prefixed with [${bookingContext.requestId}]" or null,
  "userPrompt": "A clean, friendly question for the user, e.g. 'The business needs your exact address. What is it?' — no provider codes, no raw text" or null,
  "bookingConfirmed": boolean,
  "scheduledTime": "e.g. 3:00 PM today" or null
}`;

  try {
    const text = await generateText(prompt);
    const cleaned = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim();
    return JSON.parse(cleaned);
  } catch (err) {
    console.warn('[GEMINI] analyzeProviderMessage failed:', err.message);
    const looksLikeQuestion = /\?/.test(messageBody);
    return {
      requiresUserInput: true,
      suggestedReply: null,
      userPrompt: looksLikeQuestion
        ? `The provider has a question about your ${bookingContext.serviceQuery || 'request'}. When would you like the service, and do you have any specific details to share?`
        : `The provider just replied: "${messageBody}". How would you like to respond?`,
      bookingConfirmed: false,
      scheduledTime: null,
    };
  }
}

/**
 * Compose a professional WhatsApp reply from user's casual input.
 */
async function composeUserWhatsAppReply(userReply, conversationHistory, bookingContext = {}) {
  const p = bookingContext.userProfile || {};

  const history = (conversationHistory || [])
    .slice(-6)
    .map((m) => `${m.direction === 'outbound' ? 'RabbitaAI' : 'Provider'}: ${m.message}`)
    .join('\n');

  const prompt = `You are RabbitaAI, a professional WhatsApp booking assistant replying to a service provider on behalf of the customer.

Booking context:
- Request ID: ${bookingContext.requestId || ''}
- Service: "${bookingContext.serviceQuery || ''}"
- Order details: "${bookingContext.orderDetails || bookingContext.originalRequest || ''}"
- Provider: "${bookingContext.providerName || 'the provider'}"

Customer profile (for context ONLY):
- Name: "${p.name || 'Not provided'}"
- Address: "${p.address || 'Not provided'}"
- Timing preference: "${p.timing || 'Not specified'}"
- Notes: "${p.bio || 'None'}"

Recent conversation:
${history || '(none yet)'}

The customer just replied (casual): "${userReply}"

Task: Compose ONE professional WhatsApp message to send to the provider.
- Start with [${bookingContext.requestId}]
- Translate the customer's casual reply into a polite, clear statement.
- CRITICAL PRIVACY RULE: Do NOT include the customer's exact address unless the provider EXPLICITLY asked for it in the recent conversation. Do not volunteer the address unprompted.
- Be concise (under 30 words).
- Return ONLY the message text, no quotes, no explanation`;

  let text = (await generateText(prompt)).trim();
  const reqId = bookingContext.requestId;
  if (reqId && !text.includes(`[${reqId}]`)) {
    text = `[${reqId}] ${text}`;
  }
  return text;
}

module.exports = {
  analyzeIntent,
  rankProviders,
  generateAckMessage,
  generateHelpMessage,
  analyzeProviderMessage,
  composeUserWhatsAppReply,
};
